/**
 * Song Database
 * Contains popular song melodies with their note sequences
 */

const songDatabase = [
  // ─── ORIGINAL 20: Traditional / Folk ───────────────────────────────────────
  {
    id: 1,
    title: 'Happy Birthday',
    artist: 'Traditional',
    notes: ['G4', 'G4', 'A4', 'G4', 'C5', 'B4'],
    intervals: [0, 0, 2, 0, 5, -1],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 1.0],
    key: 'G',
  },
  {
    id: 3,
    title: 'Mary Had a Little Lamb',
    artist: 'Traditional',
    notes: ['E4', 'D4', 'C4', 'D4', 'E4', 'E4', 'E4', 'D4', 'D4', 'D4', 'E4', 'G4', 'G4'],
    intervals: [0, -2, -2, 2, 0, 0, 0, -2, 0, 0, 2, 3, 0],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 1],
    key: 'C',
  },
  {
    id: 4,
    title: 'Jingle Bells',
    artist: 'Traditional',
    notes: ['E4', 'E4', 'E4', 'E4', 'E4', 'E4', 'E4', 'G4', 'C4', 'D4', 'E4'],
    intervals: [0, 0, 0, 0, 0, 0, 0, 3, -8, 2, 2],
    durations: [0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 0.5, 0.5, 1],
    key: 'E',
  },
  {
    id: 5,
    title: "Beethoven's 9th (Ode to Joy)",
    artist: 'Ludwig van Beethoven',
    notes: ['E4', 'E4', 'F4', 'G4', 'G4', 'G4', 'F4', 'E4', 'D4', 'C4', 'C4', 'D4', 'E4'],
    intervals: [0, 0, 1, 2, 0, 0, -1, -2, -2, -2, 0, 2, 2],
    durations: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
    key: 'E',
  },
  {
    id: 7,
    title: 'Old MacDonald',
    artist: 'Traditional',
    notes: ['G4', 'G4', 'G4', 'D4', 'E4', 'E4', 'D4', 'B3', 'B3', 'A3', 'A3', 'G3'],
    intervals: [0, 0, -5, 2, 0, -2, -3, 0, -2, 0, -2],
    durations: [0.5, 0.5, 1, 1, 0.5, 0.5, 1, 0.5, 0.5, 0.5, 0.5, 2],
    key: 'G',
  },
  {
    id: 8,
    title: 'Yankee Doodle',
    artist: 'Traditional',
    notes: ['G4', 'G4', 'G4', 'A4', 'B4', 'C5', 'D5'],
    intervals: [0, 0, 0, 2, 2, 2, 2],
    durations: [0.5, 0.5, 0.5, 0.5, 1, 1, 1],
    key: 'G',
  },
  {
    id: 9,
    title: 'Row Row Row Your Boat',
    artist: 'Traditional',
    notes: ['C4', 'C4', 'C4', 'D4', 'E4', 'E4', 'E4', 'F4', 'G4'],
    intervals: [0, 0, 0, 2, 2, 0, 0, 1, 2],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1],
    key: 'C',
  },
  {
    id: 10,
    title: 'Baa Baa Black Sheep',
    artist: 'Traditional',
    notes: ['C4', 'C4', 'C4', 'G4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4'],
    intervals: [0, 0, 0, 7, 2, -2, -2, -1, -2, 0],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1],
    key: 'C',
  },
  {
    id: 11,
    title: 'Amazing Grace',
    artist: 'Traditional',
    notes: ['A4', 'C5', 'E5', 'E5', 'E5', 'D5', 'C5', 'B4', 'A4'],
    intervals: [0, 3, 4, 0, 0, -2, -2, -1, -2],
    durations: [1, 1, 0.5, 0.5, 1, 1, 1, 1, 2],
    key: 'A',
  },
  {
    id: 12,
    title: 'Lullaby (Brahms)',
    artist: 'Johannes Brahms',
    notes: ['G4', 'C5', 'C5', 'C5', 'D5', 'E5', 'E5', 'E5', 'F5'],
    intervals: [0, 5, 0, 0, 2, 2, 0, 0, 1],
    durations: [1, 0.5, 0.5, 1, 1, 0.5, 0.5, 1, 1],
    key: 'G',
  },
  {
    id: 13,
    title: 'Oh Susanna',
    artist: 'Traditional',
    notes: ['G4', 'C5', 'C5', 'C5', 'C5', 'D5', 'E5', 'C5', 'E5', 'G5'],
    intervals: [0, 5, 0, 0, 0, 2, 2, -4, 4, 3],
    durations: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1, 0.5, 0.5, 1],
    key: 'G',
  },
  {
    id: 14,
    title: 'Frère Jacques',
    artist: 'Traditional',
    notes: ['C4', 'D4', 'E4', 'C4', 'C4', 'D4', 'E4', 'C4'],
    intervals: [0, 2, 2, -4, 0, 2, 2, -4],
    durations: [1, 1, 1, 1, 1, 1, 1, 2],
    key: 'C',
  },
  {
    id: 15,
    title: 'London Bridge',
    artist: 'Traditional',
    notes: ['G4', 'A4', 'G4', 'F4', 'E4', 'F4', 'G4', 'D4', 'E4', 'F4'],
    intervals: [0, 2, -2, -2, -1, 1, 2, -7, 2, 1],
    durations: [1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
    key: 'G',
  },
  {
    id: 16,
    title: 'Silent Night',
    artist: 'Traditional',
    notes: ['G4', 'A4', 'G4', 'E4', 'G4', 'A4', 'B4', 'C5', 'C5', 'B4'],
    intervals: [0, 2, -2, -4, 3, 2, 2, 2, 0, -1],
    durations: [1, 1, 1, 1, 1, 1, 1, 1, 0.5, 0.5],
    key: 'G',
  },
  {
    id: 17,
    title: 'Star Spangled Banner (First 8)',
    artist: 'Francis Scott Key',
    notes: ['E4', 'G4', 'G4', 'G4', 'A4', 'B4', 'C5', 'C5'],
    intervals: [0, 3, 0, 0, 2, 2, 2, 0],
    durations: [1, 1, 0.5, 0.5, 1, 1, 1, 1],
    key: 'E',
  },
  {
    id: 18,
    title: 'Take Me Out to the Ball Game',
    artist: 'Traditional',
    notes: ['G4', 'E4', 'G4', 'A4', 'G4', 'B4', 'A4', 'G4'],
    intervals: [0, -3, 3, 2, -2, 3, -1, -2],
    durations: [0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5],
    key: 'G',
  },
  {
    id: 19,
    title: 'We Wish You a Merry Christmas',
    artist: 'Traditional',
    notes: ['G4', 'G4', 'A4', 'G4', 'C5', 'B4', 'G4', 'G4', 'A4', 'G4', 'D5', 'C5'],
    intervals: [0, 0, 2, -2, 5, -1, -5, 0, 2, -2, 5, -2],
    durations: [0.5, 0.5, 1, 1, 1, 1, 0.5, 0.5, 1, 1, 1, 2],
    key: 'G',
  },
  {
    id: 20,
    title: 'Yankee Doodle (Extended)',
    artist: 'Traditional',
    notes: ['G4', 'A4', 'B4', 'C5', 'G4', 'G4', 'G4', 'A4', 'B4', 'C5'],
    intervals: [0, 2, 2, 2, -5, 0, 0, 2, 2, 2],
    durations: [0.5, 0.5, 0.5, 0.5, 1, 0.5, 0.5, 0.5, 0.5, 1],
    key: 'G',
  },

  // ─── CLASSICAL / ORCHESTRAL ─────────────────────────────────────────────────
  {
    id: 21,
    title: 'Symphony No. 5 (Opening)',
    artist: 'Ludwig van Beethoven',
    notes: ['G4', 'G4', 'G4', 'Eb4', 'F4', 'F4', 'F4', 'D4'],
    key: 'Cm',
  },
  {
    id: 22,
    title: 'Für Elise',
    artist: 'Ludwig van Beethoven',
    notes: ['E5', 'D#5', 'E5', 'D#5', 'E5', 'B4', 'D5', 'C5', 'A4'],
    key: 'Am',
  },
  {
    id: 23,
    title: 'Canon in D',
    artist: 'Johann Pachelbel',
    notes: ['F#5', 'E5', 'D5', 'C#5', 'B4', 'A4', 'B4', 'C#5', 'D5', 'E5'],
    key: 'D',
  },
  {
    id: 24,
    title: 'Eine Kleine Nachtmusik',
    artist: 'Wolfgang Amadeus Mozart',
    notes: ['G4', 'D5', 'D5', 'E5', 'D5', 'C5', 'B4', 'A4', 'G4'],
    key: 'G',
  },
  {
    id: 25,
    title: 'In the Hall of the Mountain King',
    artist: 'Edvard Grieg',
    notes: ['A3', 'B3', 'C4', 'D4', 'E4', 'C4', 'E4', 'D#4', 'E4', 'G4'],
    key: 'Am',
  },
  {
    id: 26,
    title: 'Morning Mood (Peer Gynt)',
    artist: 'Edvard Grieg',
    notes: ['E4', 'F#4', 'G#4', 'A4', 'B4', 'A4', 'B4', 'C#5', 'B4'],
    key: 'E',
  },
  {
    id: 27,
    title: 'William Tell Overture (Finale)',
    artist: 'Gioachino Rossini',
    notes: ['E4', 'E4', 'E4', 'C4', 'E4', 'G4', 'E4', 'E4', 'E4', 'C4'],
    key: 'E',
  },
  {
    id: 28,
    title: 'Ride of the Valkyries',
    artist: 'Richard Wagner',
    notes: ['G4', 'G4', 'Bb4', 'D5', 'G5', 'F5', 'D5', 'Bb4', 'G4'],
    key: 'Dm',
  },
  {
    id: 29,
    title: 'O Fortuna (Carmina Burana)',
    artist: 'Carl Orff',
    notes: ['G4', 'G4', 'G4', 'G4', 'F4', 'G4', 'Ab4', 'G4', 'F4', 'Eb4'],
    key: 'Gm',
  },
  {
    id: 30,
    title: 'Also Sprach Zarathustra (Opening)',
    artist: 'Richard Strauss',
    notes: ['C3', 'G3', 'C4', 'E4', 'Eb4', 'E4', 'C4'],
    key: 'C',
  },
  {
    id: 31,
    title: 'The Four Seasons — Spring',
    artist: 'Antonio Vivaldi',
    notes: ['E5', 'E5', 'E5', 'F#5', 'G#5', 'G#5', 'G#5', 'A5', 'B5'],
    key: 'E',
  },
  {
    id: 32,
    title: 'Swan Lake Theme',
    artist: 'Pyotr Tchaikovsky',
    notes: ['B4', 'D5', 'E5', 'F#5', 'E5', 'D5', 'B4', 'E5', 'C#5', 'A4'],
    key: 'Bm',
  },
  {
    id: 33,
    title: 'Moonlight Sonata (Opening)',
    artist: 'Ludwig van Beethoven',
    notes: ['G#3', 'C#4', 'E4', 'G#3', 'C#4', 'E4', 'A3', 'C#4', 'E4'],
    key: 'C#m',
  },

  // ─── FILM & TV SCORES ────────────────────────────────────────────────────────
  {
    id: 34,
    title: 'Star Wars — Main Theme',
    artist: 'John Williams',
    notes: ['G4', 'G4', 'G4', 'D4', 'Bb4', 'A4', 'G4', 'D4', 'Bb4', 'A4', 'G4'],
    key: 'Bb',
  },
  {
    id: 35,
    title: 'Imperial March (Darth Vader)',
    artist: 'John Williams',
    notes: ['G4', 'G4', 'G4', 'Eb4', 'Bb4', 'G4', 'Eb4', 'Bb4', 'G4'],
    key: 'Gm',
  },
  {
    id: 36,
    title: "Hedwig's Theme (Harry Potter)",
    artist: 'John Williams',
    notes: ['B4', 'E5', 'G5', 'F#5', 'E5', 'B5', 'A5', 'F#5'],
    key: 'Em',
  },
  {
    id: 37,
    title: 'Indiana Jones Theme (Raiders March)',
    artist: 'John Williams',
    notes: ['C4', 'D4', 'F4', 'G4', 'C5', 'Bb4', 'A4', 'G4', 'F4'],
    key: 'F',
  },
  {
    id: 38,
    title: 'Jurassic Park Theme',
    artist: 'John Williams',
    notes: ['A4', 'B4', 'C#5', 'A4', 'E5', 'D5', 'A4', 'B4', 'C#5', 'A4'],
    key: 'A',
  },
  {
    id: 39,
    title: "Schindler's List Theme",
    artist: 'John Williams',
    notes: ['B4', 'E5', 'G5', 'F#5', 'E5', 'D5', 'C#5', 'D5', 'B4'],
    key: 'Bm',
  },
  {
    id: 40,
    title: 'Game of Thrones Theme',
    artist: 'Ramin Djawadi',
    notes: ['G4', 'C5', 'Eb5', 'F5', 'G4', 'C5', 'Eb5', 'F5', 'G5'],
    key: 'Cm',
  },
  {
    id: 41,
    title: "Pirates of the Caribbean — He's a Pirate",
    artist: 'Klaus Badelt',
    notes: ['D4', 'D4', 'E4', 'D4', 'F4', 'E4', 'D4', 'A3', 'Bb3', 'A3', 'D4'],
    key: 'Dm',
  },
  {
    id: 42,
    title: 'Mission: Impossible Theme',
    artist: 'Lalo Schifrin',
    notes: ['E4', 'F4', 'E4', 'Eb4', 'E4', 'F4', 'E4', 'Eb4', 'E4'],
    key: 'Em',
  },
  {
    id: 43,
    title: 'James Bond Theme',
    artist: 'Monty Norman',
    notes: ['E4', 'F#4', 'F#4', 'F#4', 'F#4', 'E4', 'E4', 'E4', 'G4', 'G4', 'G4'],
    key: 'Em',
  },
  {
    id: 44,
    title: 'The Godfather Theme',
    artist: 'Nino Rota',
    notes: ['E4', 'A4', 'B4', 'C5', 'B4', 'A4', 'E4', 'A4', 'B4', 'C5', 'D5'],
    key: 'Am',
  },
  {
    id: 45,
    title: 'Pink Panther Theme',
    artist: 'Henry Mancini',
    notes: ['C#4', 'D4', 'F4', 'G4', 'Eb4', 'D4', 'C#4', 'D4', 'F4', 'Ab4'],
    key: 'Dm',
  },

  // ─── VIDEO GAMES ─────────────────────────────────────────────────────────────
  {
    id: 46,
    title: 'Super Mario Bros. Theme',
    artist: 'Koji Kondo',
    notes: ['E5', 'E5', 'E5', 'C5', 'E5', 'G5', 'G4', 'C5', 'G4', 'E4'],
    key: 'C',
  },
  {
    id: 47,
    title: 'Tetris Theme (Korobeiniki)',
    artist: 'Traditional / Hirokazu Tanaka',
    notes: ['E5', 'B4', 'C5', 'D5', 'C5', 'B4', 'A4', 'A4', 'C5', 'E5', 'D5', 'C5'],
    key: 'Am',
  },
  {
    id: 48,
    title: 'The Legend of Zelda Theme',
    artist: 'Koji Kondo',
    notes: ['D4', 'G4', 'A4', 'Bb4', 'A4', 'G4', 'E4', 'F#4', 'G4', 'A4'],
    key: 'G',
  },
  {
    id: 49,
    title: 'Pokemon Main Theme',
    artist: 'Junichi Masuda',
    notes: ['E4', 'E4', 'E4', 'G4', 'E4', 'E4', 'D4', 'E4', 'G4', 'E4'],
    key: 'E',
  },
  {
    id: 50,
    title: 'Final Fantasy — Victory Fanfare',
    artist: 'Nobuo Uematsu',
    notes: ['C4', 'C4', 'C4', 'C4', 'Eb4', 'F4', 'G4', 'G4', 'Eb4', 'F4', 'G4'],
    key: 'C',
  },
  {
    id: 51,
    title: 'Sonic — Green Hill Zone',
    artist: 'Masato Nakamura',
    notes: ['E5', 'D5', 'C5', 'A4', 'B4', 'C5', 'D5', 'E5', 'G5', 'E5'],
    key: 'C',
  },
  {
    id: 52,
    title: 'Halo Theme',
    artist: "Martin O'Donnell",
    notes: ['A4', 'C5', 'A4', 'G4', 'F4', 'G4', 'A4', 'C5', 'A4', 'G4'],
    key: 'Am',
  },

  // ─── CLASSIC ROCK ────────────────────────────────────────────────────────────
  {
    id: 53,
    title: 'Seven Nation Army',
    artist: 'The White Stripes',
    notes: ['E3', 'E3', 'G3', 'E3', 'E3', 'D3', 'C3', 'B2'],
    key: 'Em',
  },
  {
    id: 54,
    title: 'Smoke on the Water',
    artist: 'Deep Purple',
    notes: ['G3', 'Bb3', 'C4', 'G3', 'Bb3', 'Db4', 'C4', 'G3', 'Bb3', 'C4', 'Bb3'],
    key: 'Gm',
  },
  {
    id: 55,
    title: "Sweet Child O' Mine",
    artist: "Guns N' Roses",
    notes: ['D5', 'D4', 'A4', 'G4', 'D5', 'D4', 'A4', 'G4', 'E5', 'D4', 'A4'],
    key: 'D',
  },
  {
    id: 56,
    title: 'Eye of the Tiger',
    artist: 'Survivor',
    notes: ['C5', 'C5', 'Bb4', 'C5', 'Ab4', 'G4', 'F4', 'G4', 'Ab4', 'G4'],
    key: 'Cm',
  },
  {
    id: 57,
    title: "Don't Stop Believin'",
    artist: 'Journey',
    notes: ['E4', 'F#4', 'G#4', 'A4', 'B4', 'C#5', 'B4', 'A4', 'G#4'],
    key: 'E',
  },
  {
    id: 58,
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    notes: ['Bb4', 'Bb4', 'Bb4', 'F4', 'G4', 'Bb4', 'Ab4', 'G4', 'F4', 'Bb3'],
    key: 'Bb',
  },
  {
    id: 59,
    title: 'Stairway to Heaven (Intro)',
    artist: 'Led Zeppelin',
    notes: ['A4', 'C5', 'E5', 'A5', 'C5', 'B4', 'A4', 'C5', 'E5', 'G5'],
    key: 'Am',
  },
  {
    id: 60,
    title: 'Smells Like Teen Spirit',
    artist: 'Nirvana',
    notes: ['F4', 'F4', 'F4', 'Bb4', 'Bb4', 'Bb4', 'Ab4', 'Ab4', 'Ab4', 'Db4'],
    key: 'F',
  },
  {
    id: 61,
    title: 'Under Pressure',
    artist: 'Queen & David Bowie',
    notes: ['D4', 'D4', 'D4', 'D4', 'C4', 'B3', 'G3', 'A3', 'G3', 'A3'],
    key: 'D',
  },
  {
    id: 62,
    title: 'Back in Black',
    artist: 'AC/DC',
    notes: ['E3', 'A3', 'D4', 'D4', 'A3', 'E3', 'D4', 'D4', 'A3', 'E3'],
    key: 'E',
  },
  {
    id: 63,
    title: 'Enter Sandman',
    artist: 'Metallica',
    notes: ['E3', 'G3', 'E3', 'G3', 'E3', 'F#3', 'E3', 'F3', 'E3'],
    key: 'Em',
  },
  {
    id: 64,
    title: 'Wonderwall',
    artist: 'Oasis',
    notes: ['B4', 'B4', 'B4', 'C#5', 'D#5', 'C#5', 'B4', 'A4', 'B4'],
    key: 'F#m',
  },
  {
    id: 65,
    title: 'Mr. Brightside',
    artist: 'The Killers',
    notes: ['Bb3', 'Eb4', 'F4', 'G4', 'Bb4', 'C5', 'Bb4', 'Ab4', 'G4'],
    key: 'Eb',
  },

  // ─── POP / SOUL ──────────────────────────────────────────────────────────────
  {
    id: 66,
    title: 'Let It Be',
    artist: 'The Beatles',
    notes: ['C4', 'D4', 'E4', 'G4', 'A4', 'G4', 'E4', 'G4', 'A4', 'C5'],
    key: 'C',
  },
  {
    id: 67,
    title: 'Hey Jude',
    artist: 'The Beatles',
    notes: ['F4', 'F4', 'E4', 'F4', 'Bb4', 'A4', 'G4', 'F4', 'G4'],
    key: 'F',
  },
  {
    id: 68,
    title: 'Yesterday',
    artist: 'The Beatles',
    notes: ['F5', 'E5', 'D5', 'C#5', 'D5', 'F5', 'A4', 'Bb4', 'C5'],
    key: 'F',
  },
  {
    id: 69,
    title: 'Take On Me',
    artist: 'a-ha',
    notes: ['F#5', 'F#5', 'D5', 'B4', 'B4', 'E5', 'E5', 'E5', 'G#5', 'A5'],
    key: 'A',
  },
  {
    id: 70,
    title: 'Sweet Dreams (Are Made of This)',
    artist: 'Eurythmics',
    notes: ['A4', 'C5', 'B4', 'C5', 'D5', 'C5', 'B4', 'A4', 'B4', 'C5'],
    key: 'Am',
  },
  {
    id: 71,
    title: 'Africa',
    artist: 'Toto',
    notes: ['A4', 'A4', 'C#5', 'B4', 'A4', 'G#4', 'A4', 'A4', 'C#5', 'B4'],
    key: 'A',
  },
  {
    id: 72,
    title: 'Piano Man',
    artist: 'Billy Joel',
    notes: ['G4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4', 'E4', 'G4'],
    key: 'C',
  },
  {
    id: 73,
    title: 'Rocket Man',
    artist: 'Elton John',
    notes: ['Bb4', 'Bb4', 'C5', 'Bb4', 'Ab4', 'Bb4', 'G4', 'F4', 'Eb4'],
    key: 'Bb',
  },
  {
    id: 74,
    title: 'Imagine',
    artist: 'John Lennon',
    notes: ['C4', 'E4', 'F4', 'E4', 'D4', 'C4', 'D4', 'E4', 'G4', 'E4'],
    key: 'C',
  },
  {
    id: 75,
    title: 'Billie Jean',
    artist: 'Michael Jackson',
    notes: ['F#4', 'F#4', 'A4', 'F#4', 'F#4', 'E4', 'F#4', 'A4', 'F#4'],
    key: 'F#m',
  },
  {
    id: 76,
    title: 'Superstition',
    artist: 'Stevie Wonder',
    notes: ['Eb4', 'Eb4', 'Eb4', 'G4', 'Eb4', 'Eb4', 'Db4', 'Eb4', 'G4'],
    key: 'Eb',
  },
  {
    id: 77,
    title: 'I Will Always Love You',
    artist: 'Whitney Houston',
    notes: ['A4', 'A4', 'B4', 'A4', 'D5', 'C#5', 'B4', 'A4', 'B4', 'A4'],
    key: 'A',
  },
  {
    id: 78,
    title: 'Rolling in the Deep',
    artist: 'Adele',
    notes: ['C4', 'C4', 'C4', 'Eb4', 'F4', 'Ab4', 'G4', 'F4', 'Eb4', 'C4'],
    key: 'Cm',
  },
  {
    id: 79,
    title: 'Someone Like You',
    artist: 'Adele',
    notes: ['A4', 'A4', 'B4', 'C#5', 'B4', 'A4', 'G#4', 'A4', 'B4', 'C#5'],
    key: 'A',
  },
  {
    id: 80,
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    notes: ['C#4', 'D#4', 'E4', 'G#4', 'F#4', 'E4', 'C#4', 'B3', 'C#4'],
    key: 'C#m',
  },

  // ─── ADDITIONAL FOLK / TRADITIONAL ──────────────────────────────────────────
  {
    id: 81,
    title: 'Greensleeves',
    artist: 'Traditional',
    notes: ['A4', 'C5', 'D5', 'E5', 'D5', 'C5', 'A4', 'F4', 'G4', 'A4'],
    key: 'Am',
  },
  {
    id: 82,
    title: 'Scarborough Fair',
    artist: 'Traditional',
    notes: ['A4', 'D5', 'E5', 'A5', 'G5', 'E5', 'D5', 'A4', 'E4'],
    key: 'Am',
  },
  {
    id: 83,
    title: 'Ode to Joy (Extended)',
    artist: 'Ludwig van Beethoven',
    notes: ['E4', 'E4', 'F4', 'G4', 'G4', 'F4', 'E4', 'D4', 'C4', 'C4', 'D4', 'E4', 'E4', 'D4'],
    key: 'C',
  },
];

export { songDatabase };
